# Generated by Django 4.2 on 2023-07-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_projectpeak_academia_alter_course_projects_count_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectPeak_Academia",
            new_name="ProjectPeakAcademia",
        ),
    ]
