# Generated by Django 4.2 on 2023-07-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_projectpeak_academia_projectpeakacademia"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="users_that_found_this_project_useful",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="course",
            name="url",
            field=models.SlugField(
                blank=True, editable=False, max_length=10000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="format",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="project",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.SlugField(
                blank=True, editable=False, max_length=10000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="email",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
