# Generated by Django 4.2 on 2023-07-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="project",
            name="users_that_found_this_project_useful",
            field=models.IntegerField(),
        ),
    ]
