# Generated by Django 4.2 on 2023-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_project_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpeakacademia",
            name="account_name",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name="projectpeakacademia",
            name="account_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectpeakacademia",
            name="bank_name",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
