# Generated by Django 4.2 on 2023-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projectpeakacademia_account_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=10000, null=True)),
                ("phone_number", models.IntegerField()),
                ("email", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "project_title",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("project_details", models.TextField()),
            ],
        ),
    ]
