# Generated by Django 4.2 on 2023-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_project_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_request",
            name="course_of_study",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
