# Generated by Django 4.2 on 2023-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_project_request_course_of_study"),
    ]

    operations = [
        migrations.CreateModel(
            name="Our_Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=10000)),
                ("service_description", models.TextField()),
            ],
        ),
    ]
