# Generated by Django 4.2.4 on 2023-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_projectpeakacademia_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpeakacademia",
            name="account_number",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
